version: '3.8'

services:

  # Create Postgres DB
  db:
    container_name: postgresDB
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  # Create FastAPI app
  app:
      container_name: src
      build:
        context: .\src
        dockerfile: dockerFile
      command: bash -c "cd /src/db && alembic upgrade head && cd .. && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
      volumes:
        - ./src:/src
      ports:
        - 8000:8000
      depends_on:
        - db
      restart: always
      environment:
        DATABASE_URL: ${DATABASE_URL}