version: '3.8'

services:

  # Create Postgres DB
  testdb:
    container_name: test_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - 3000:3000

  # Create Test FastAPI app
  # app:
  #     container_name: test_app
  #     build:
  #       dockerfile: Dockerfile
  #     command: bash -c "cd /src/db && alembic upgrade head && cd .. && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
  #     volumes:
  #       - ./src:/src
  #     ports:
  #       - 8000:8000
  #     depends_on:
  #       - testdb
  #     restart: always
  #     environment:
  #       DATABASE_URL: ${TEST_DATABASE_URL}
  #       SECRET_KEY: ${SECRET_KEY}
  #       ALGORITHM: ${ALGORITHM}