"""Add holiday fields

Revision ID: 35f250ed00e1
Revises: fc4695d86cd7
Create Date: 2025-02-21 14:52:59.308493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f250ed00e1'
down_revision = 'fc4695d86cd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Roles', ['name'])
    op.create_unique_constraint(None, 'Teams', ['name'])
    op.add_column('Users', sa.Column('number_of_allocated_holdiays', sa.Integer(), nullable=False, server_default='28'))
    op.add_column('Users', sa.Column('number_of_remaining_holidays', sa.Integer(), nullable=False, server_default='28'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'number_of_remaining_holidays')
    op.drop_column('Users', 'number_of_allocated_holdiays')
    op.drop_constraint(None, 'Teams', type_='unique')
    op.drop_constraint(None, 'Roles', type_='unique')
    # ### end Alembic commands ###
