"""Inital Migration 3

Revision ID: 978ebbd641a8
Revises: 
Create Date: 2023-09-05 20:26:34.236991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978ebbd641a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Teams',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role_name'], ['Roles.name'], ),
    sa.ForeignKeyConstraint(['team_name'], ['Teams.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('HolidayRequests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('morning_or_afternoon', sa.String(length=2), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_name'], ['Teams.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('HolidayRequests')
    op.drop_table('Users')
    op.drop_table('Teams')
    op.drop_table('Roles')
    # ### end Alembic commands ###
