"""make userMdoel and schema identical

Revision ID: d3aae598e7a8
Revises: f3561fb5e797
Create Date: 2023-08-10 15:26:00.338049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3aae598e7a8'
down_revision = 'f3561fb5e797'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('full_name', sa.String(), nullable=True))
    op.drop_column('Users', 'fullName')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('fullName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Users', 'full_name')
    # ### end Alembic commands ###
