"""fix teamAndrole

Revision ID: da751dff79b4
Revises: ca7e709fdf67
Create Date: 2023-08-27 15:06:02.569806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da751dff79b4'
down_revision = 'ca7e709fdf67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Roles', ['name'])
    op.create_unique_constraint(None, 'Teams', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Teams', type_='unique')
    op.drop_constraint(None, 'Roles', type_='unique')
    # ### end Alembic commands ###
