"""makeIdsUnique

Revision ID: f3561fb5e797
Revises: 379f0da0b2a9
Create Date: 2023-08-09 09:34:32.497481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3561fb5e797'
down_revision = '379f0da0b2a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Roles', ['name'])
    op.create_unique_constraint(None, 'Teams', ['name'])
    op.create_unique_constraint(None, 'Users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_constraint(None, 'Teams', type_='unique')
    op.drop_constraint(None, 'Roles', type_='unique')
    # ### end Alembic commands ###
