"""fix fieldNaming

Revision ID: 52df60043934
Revises: da751dff79b4
Create Date: 2023-08-27 15:29:17.690536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52df60043934'
down_revision = 'da751dff79b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('Fullname', sa.String(), nullable=True))
    op.drop_column('Users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Users', 'Fullname')
    # ### end Alembic commands ###
