name: 'Build'

on:
  workflow_dispatch:
     branches:
      - master
  push:
    branches:
      - master
  pull_request:
    types:
      - merged
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3 # Checkout the repository to github runner

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13' # Install exact Python version

      - name: Install python packages # Install all dependencies used
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run python tests
        env:
          PYTHONPATH: src  # Add src to PYTHONPATH
        run: |
          python -m unittest discover -s src/tests -p test_*.py