name: 'Build'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - merged
      - closed
  # schedule:
  #   - branch: main
  #     cron: '0 0 * * *' # Run every day at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3 # Checkout the repository to github runner

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13' # Install exact Python version
          cache: 'pip' # Cache the pip packages

      - name: Install python packages # Install all dependencies used
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run python tests
        run: |
          python -m unittest discover -s src/tests -p test_*.py
          
      - name: Run the py script
        run: |
          python src/main.py

      # - name: Commit and push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: main
      #     commit_user_name: github-actions[bot]
      #     commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
      #     commit_message: "Update holidays"