# github action.yml
name: 'Test Python Application'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - merged
      - closed
  # schedule:
  #   - branch: main
  #     cron: '0 0 * * *' # Run every day at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # - name: Checkout the repository
      #   uses: ./.github/actions/checkout # Use local checkout action

      - name: Checkout the repository
        uses: actions/checkout@v3 # Use the official checkout action

      - name: Setup Python
        uses: ./.github/actions/setup-python # Use local setup-python action
        with:
          python-version: '3.9.13' # Install exact Python version

      - name: Install python packages # Install all dependencies used
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run python tests
        run: |
          python -m unittest discover -s tests -p test_*.py
          
      - name: Run the py script # Run the main python script to check if it runs
        run: |
          python src/main.py